// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using SmartCar.Infrastructure.Persistence;

#nullable disable

namespace SmartCar.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260920134500_PreserveRefundLedgerReference")]
    partial class PreserveRefundLedgerReference
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            ApplicationDbContextModelSnapshot.BuildMigration20260916180000(modelBuilder);
#pragma warning restore 612, 618
        }
    }
}
