// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using SmartCar.Infrastructure.Persistence;

#nullable disable

namespace SmartCar.Infrastructure.Persistence.Migrations;

[DbContext(typeof(ApplicationDbContext))]
partial class ApplicationDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        BuildPart1(modelBuilder);
        BuildPart2(modelBuilder);
        BuildPart3(modelBuilder);
        BuildPart4(modelBuilder);
        BuildPart5(modelBuilder);
#pragma warning restore 612, 618
    }
}
