// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace SmartCar.Infrastructure.Persistence.Migrations;

partial class ApplicationDbContextModelSnapshot
{
    private static void BuildPart3(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity("SmartCar.Domain.Entities.Vehicle", b =>
            {
                b.Property<int>("VehicleId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                b.Property<int>("BrandId")
                    .HasColumnType("int");

                b.Property<string>("Color")
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<int>("CurrentMileage")
                    .HasColumnType("int");

                b.Property<decimal>("DailyPrice")
                    .HasPrecision(18, 2)
                    .HasColumnType("decimal(18,2)");

                b.Property<string>("Description")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("FuelType")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("nvarchar(30)");

                b.Property<string>("LicensePlate")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.Property<int>("ManufactureYear")
                    .HasColumnType("int");

                b.Property<string>("Model")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<byte[]>("RowVersion")
                    .IsConcurrencyToken()
                    .IsRequired()
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("rowversion");

                b.Property<int>("Seats")
                    .HasColumnType("int");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("nvarchar(30)");

                b.Property<string>("Transmission")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("nvarchar(30)");

                b.Property<string>("VehicleName")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("nvarchar(150)");

                b.HasKey("VehicleId");

                b.HasIndex("BrandId");

                b.HasIndex("LicensePlate")
                    .IsUnique();

                b.ToTable("Vehicles");
            });

        modelBuilder.Entity("SmartCar.Domain.Entities.VehicleDocument", b =>
            {
                b.Property<int>("VehicleDocumentId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleDocumentId"));

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("DocumentNumber")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("DocumentType")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("nvarchar(30)");

                b.Property<DateTime?>("ExpiryDate")
                    .HasColumnType("datetime2");

                b.Property<string>("ImagePath")
                    .HasMaxLength(300)
                    .HasColumnType("nvarchar(300)");

                b.Property<DateTime>("IssuedDate")
                    .HasColumnType("datetime2");

                b.Property<string>("Notes")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<int>("VehicleId")
                    .HasColumnType("int");

                b.HasKey("VehicleDocumentId");

                b.HasIndex("VehicleId", "DocumentType", "ExpiryDate");

                b.ToTable("VehicleDocuments");
            });

        modelBuilder.Entity("SmartCar.Domain.Entities.VehicleHandover", b =>
            {
                b.Property<int>("VehicleHandoverId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleHandoverId"));

                b.Property<string>("Accessories")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("BookingId")
                    .HasColumnType("int");

                b.Property<bool>("CustomerIdentityVerified")
                    .HasColumnType("bit");

                b.Property<string>("DamageCompensationTerms")
                    .IsRequired()
                    .HasMaxLength(1500)
                    .HasColumnType("nvarchar(1500)");

                b.Property<decimal>("ExcessKmFeePerKm")
                    .HasPrecision(18, 2)
                    .HasColumnType("decimal(18,2)");

                b.Property<string>("ExteriorCondition")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("FuelLevel")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("nvarchar(30)");

                b.Property<DateTime>("HandoverAt")
                    .HasColumnType("datetime2");

                b.Property<DateTime?>("IdentityVerifiedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("IdentityVerifiedByStaffId")
                    .HasMaxLength(450)
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("ImagePaths")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("IncludedKilometers")
                    .HasColumnType("int");

                b.Property<string>("InteriorCondition")
                    .HasColumnType("nvarchar(max)");

                b.Property<decimal>("LateReturnFeeMultiplier")
                    .HasPrecision(6, 2)
                    .HasColumnType("decimal(6,2)");

                b.Property<int>("Mileage")
                    .HasColumnType("int");

                b.Property<string>("Notes")
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("PenaltyPolicyAccepted")
                    .HasColumnType("bit");

                b.Property<bool>("SignedDocumentVerified")
                    .HasColumnType("bit");

                b.Property<DateTime?>("SignedDocumentVerifiedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("SignedDocumentVerifiedByStaffId")
                    .HasMaxLength(450)
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("TrafficFineTerms")
                    .IsRequired()
                    .HasMaxLength(1500)
                    .HasColumnType("nvarchar(1500)");

                b.HasKey("VehicleHandoverId");

                b.HasIndex("BookingId")
                    .IsUnique();

                b.ToTable("VehicleHandovers");
            });

        modelBuilder.Entity("SmartCar.Domain.Entities.VehicleImage", b =>
            {
                b.Property<int>("VehicleImageId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleImageId"));

                b.Property<string>("ImagePath")
                    .IsRequired()
                    .HasMaxLength(300)
                    .HasColumnType("nvarchar(300)");

                b.Property<bool>("IsPrimary")
                    .HasColumnType("bit");

                b.Property<int>("SortOrder")
                    .HasColumnType("int");

                b.Property<int>("VehicleId")
                    .HasColumnType("int");

                b.HasKey("VehicleImageId");

                b.HasIndex("VehicleId");

                b.ToTable("VehicleImages");
            });

        modelBuilder.Entity("SmartCar.Domain.Entities.VehicleIncident", b =>
            {
                b.Property<int>("VehicleIncidentId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleIncidentId"));

                b.Property<decimal>("ActualCost")
                    .HasPrecision(18, 2)
                    .HasColumnType("decimal(18,2)");

                b.Property<int?>("BookingId")
                    .HasColumnType("int");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<decimal>("CustomerLiabilityAmount")
                    .HasPrecision(18, 2)
                    .HasColumnType("decimal(18,2)");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasMaxLength(1500)
                    .HasColumnType("nvarchar(1500)");

                b.Property<decimal>("EstimatedCost")
                    .HasPrecision(18, 2)
                    .HasColumnType("decimal(18,2)");

                b.Property<string>("EvidencePaths")
                    .HasMaxLength(2000)
                    .HasColumnType("nvarchar(2000)");

                b.Property<decimal>("FineAmount")
                    .HasPrecision(18, 2)
                    .HasColumnType("decimal(18,2)");

                b.Property<string>("IncidentType")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("nvarchar(30)");

                b.Property<string>("Location")
                    .HasMaxLength(250)
                    .HasColumnType("nvarchar(250)");

                b.Property<string>("Notes")
                    .HasMaxLength(1000)
                    .HasColumnType("nvarchar(1000)");

                b.Property<DateTime>("OccurredAt")
                    .HasColumnType("datetime2");

                b.Property<DateTime?>("ResolvedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("nvarchar(30)");

                b.Property<int>("VehicleId")
                    .HasColumnType("int");

                b.HasKey("VehicleIncidentId");

                b.HasIndex("BookingId");

                b.HasIndex("VehicleId", "Status", "OccurredAt");

                b.ToTable("VehicleIncidents");
            });
    }
}
