// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace SmartCar.Infrastructure.Persistence.Migrations;

partial class ApplicationDbContextModelSnapshot
{
    private static void BuildPart8(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity("SmartCar.Domain.Entities.Booking", b =>
        {
            b.Property<string>("HandlingStaffId")
                .HasMaxLength(450)
                .HasColumnType("nvarchar(450)");

            b.Property<DateTime?>("HandlingLeaseExpiresAt")
                .HasColumnType("datetime2");
        });
    }
}
