// <auto-generated />
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace SmartCar.Infrastructure.Persistence.Migrations;

partial class ApplicationDbContextModelSnapshot
{
    internal static void BuildMigration20260916180000(ModelBuilder modelBuilder)
    {
        BuildMigration20260916173924(modelBuilder);
        BuildPart7(modelBuilder);
    }

    private static void BuildPart7(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity("SmartCar.Domain.Entities.VehicleReturn", b =>
        {
            b.Property<string>("AccessoryStatus")
                .HasMaxLength(1000)
                .HasColumnType("nvarchar(1000)");
        });
    }
}
