// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace SmartCar.Infrastructure.Persistence.Migrations;

partial class ApplicationDbContextModelSnapshot
{
    private static void BuildPart5(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity("SmartCar.Infrastructure.Identity.ApplicationUser", b =>
        {
            b.Property<string>("EmployeeCode")
                .HasMaxLength(30)
                .HasColumnType("nvarchar(30)");

            b.Property<string>("CitizenIdNumber")
                .HasMaxLength(20)
                .HasColumnType("nvarchar(20)");

            b.Property<string>("CreatedByUserId")
                .HasMaxLength(450)
                .HasColumnType("nvarchar(450)");

            b.Property<string>("VerifiedByUserId")
                .HasMaxLength(450)
                .HasColumnType("nvarchar(450)");

            b.Property<DateTime?>("VerifiedAt")
                .HasColumnType("datetime2");

            b.Property<bool>("MustChangePassword")
                .HasColumnType("bit");

            b.HasIndex("EmployeeCode")
                .IsUnique()
                .HasFilter("[EmployeeCode] IS NOT NULL");

            b.HasIndex("CitizenIdNumber")
                .IsUnique()
                .HasFilter("[CitizenIdNumber] IS NOT NULL");
        });
    }
}
