// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace SmartCar.Infrastructure.Persistence.Migrations;

partial class ApplicationDbContextModelSnapshot
{
    private static void BuildPart2(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity("SmartCar.Domain.Entities.BookingExtension", b =>
            {
                b.Property<int>("BookingExtensionId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingExtensionId"));

                b.Property<decimal>("AdditionalAmount")
                    .HasPrecision(18, 2)
                    .HasColumnType("decimal(18,2)");

                b.Property<int>("AdditionalDays")
                    .HasColumnType("int");

                b.Property<string>("AdminNote")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<int>("BookingId")
                    .HasColumnType("int");

                b.Property<string>("CustomerNote")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<DateTime?>("DecidedAt")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("OriginalReturnDate")
                    .HasColumnType("datetime2");

                b.Property<DateTime?>("PaidAt")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("RequestedAt")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("RequestedReturnDate")
                    .HasColumnType("datetime2");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("nvarchar(30)");

                b.HasKey("BookingExtensionId");

                b.HasIndex("BookingId", "Status");

                b.ToTable("BookingExtensions");
            });

        modelBuilder.Entity("SmartCar.Domain.Entities.Brand", b =>
            {
                b.Property<int>("BrandId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrandId"));

                b.Property<string>("BrandName")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit");

                b.HasKey("BrandId");

                b.HasIndex("BrandName")
                    .IsUnique();

                b.ToTable("Brands");
            });

        modelBuilder.Entity("SmartCar.Domain.Entities.CustomerDocument", b =>
            {
                b.Property<int>("CustomerDocumentId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerDocumentId"));

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("CustomerId")
                    .IsRequired()
                    .HasMaxLength(450)
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("DocumentNumber")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("DocumentType")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("nvarchar(30)");

                b.Property<DateTime?>("ExpiryDate")
                    .HasColumnType("datetime2");

                b.Property<string>("ImagePath")
                    .IsRequired()
                    .HasMaxLength(300)
                    .HasColumnType("nvarchar(300)");

                b.Property<string>("RejectionReason")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("nvarchar(30)");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.Property<DateTime?>("VerifiedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("VerifiedBy")
                    .HasMaxLength(450)
                    .HasColumnType("nvarchar(450)");

                b.HasKey("CustomerDocumentId");

                b.HasIndex("CustomerId", "DocumentType")
                    .IsUnique();

                b.ToTable("CustomerDocuments");
            });

        modelBuilder.Entity("SmartCar.Domain.Entities.MaintenanceRecord", b =>
            {
                b.Property<int>("MaintenanceRecordId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaintenanceRecordId"));

                b.Property<DateTime?>("CompletedDate")
                    .HasColumnType("datetime2");

                b.Property<string>("Content")
                    .IsRequired()
                    .HasMaxLength(1000)
                    .HasColumnType("nvarchar(1000)");

                b.Property<decimal>("Cost")
                    .HasPrecision(18, 2)
                    .HasColumnType("decimal(18,2)");

                b.Property<int>("Mileage")
                    .HasColumnType("int");

                b.Property<string>("ServiceProvider")
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<DateTime>("StartDate")
                    .HasColumnType("datetime2");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("nvarchar(30)");

                b.Property<int>("VehicleId")
                    .HasColumnType("int");

                b.HasKey("MaintenanceRecordId");

                b.HasIndex("VehicleId");

                b.ToTable("MaintenanceRecords");
            });

        modelBuilder.Entity("SmartCar.Domain.Entities.Notification", b =>
            {
                b.Property<int>("NotificationId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<bool>("IsRead")
                    .HasColumnType("bit");

                b.Property<string>("Message")
                    .IsRequired()
                    .HasMaxLength(1000)
                    .HasColumnType("nvarchar(1000)");

                b.Property<DateTime?>("ReadAt")
                    .HasColumnType("datetime2");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasMaxLength(450)
                    .HasColumnType("nvarchar(450)");

                b.HasKey("NotificationId");

                b.HasIndex("UserId", "IsRead");

                b.ToTable("Notifications");
            });

        modelBuilder.Entity("SmartCar.Domain.Entities.Payment", b =>
            {
                b.Property<int>("PaymentId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                b.Property<decimal>("Amount")
                    .HasPrecision(18, 2)
                    .HasColumnType("decimal(18,2)");

                b.Property<int>("BookingId")
                    .HasColumnType("int");

                b.Property<string>("LedgerReference")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Method")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<DateTime?>("PaidAt")
                    .HasColumnType("datetime2");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("nvarchar(30)");

                b.Property<string>("TransactionCode")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Type")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("nvarchar(30)");

                b.Property<int?>("VehicleIncidentId")
                    .HasColumnType("int");

                b.HasKey("PaymentId");

                b.HasIndex("VehicleIncidentId");

                b.HasIndex("BookingId", "Type", "Status");

                b.ToTable("Payments");
            });

        modelBuilder.Entity("SmartCar.Domain.Entities.Review", b =>
            {
                b.Property<int>("ReviewId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                b.Property<int>("BookingId")
                    .HasColumnType("int");

                b.Property<string>("Comment")
                    .HasMaxLength(1000)
                    .HasColumnType("nvarchar(1000)");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<int>("Rating")
                    .HasColumnType("int");

                b.HasKey("ReviewId");

                b.HasIndex("BookingId")
                    .IsUnique();

                b.ToTable("Reviews");
            });
    }
}
