// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace SmartCar.Infrastructure.Persistence.Migrations;

partial class ApplicationDbContextModelSnapshot
{
    internal static void BuildMigration20260916173924(ModelBuilder modelBuilder)
    {
        BuildPart1(modelBuilder);
        BuildPart2(modelBuilder);
        BuildPart3(modelBuilder);
        BuildPart4(modelBuilder);
        BuildPart5(modelBuilder);
        BuildPart6(modelBuilder);
    }

    private static void BuildPart6(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity("SmartCar.Domain.Entities.Booking", b =>
        {
            b.Property<DateTime?>("StaffReviewedAt")
                .HasColumnType("datetime2");

            b.Property<string>("StaffReviewedByStaffId")
                .HasMaxLength(450)
                .HasColumnType("nvarchar(450)");
        });

        modelBuilder.Entity("SmartCar.Domain.Entities.VehicleHandover", b =>
        {
            b.Property<string>("ReceiverFaceCaptureMethod")
                .HasColumnType("nvarchar(max)");

            b.Property<DateTime?>("ReceiverFaceCapturedAt")
                .HasColumnType("datetime2");

            b.Property<string>("ReceiverFaceImagePath")
                .HasMaxLength(500)
                .HasColumnType("nvarchar(500)");
        });

        modelBuilder.Entity("SmartCar.Domain.Entities.VehicleReturn", b =>
        {
            b.Property<string>("ReturnerFaceCaptureMethod")
                .HasColumnType("nvarchar(max)");

            b.Property<DateTime?>("ReturnerFaceCapturedAt")
                .HasColumnType("datetime2");

            b.Property<string>("ReturnerFaceImagePath")
                .HasMaxLength(500)
                .HasColumnType("nvarchar(500)");
        });

        modelBuilder.Entity("SmartCar.Infrastructure.Identity.ApplicationUser", b =>
        {
            b.Property<string>("IdentityFaceCaptureMethod")
                .HasMaxLength(50)
                .HasColumnType("nvarchar(50)");

            b.Property<DateTime?>("IdentityFaceCapturedAt")
                .HasColumnType("datetime2");

            b.Property<string>("IdentityFaceImagePath")
                .HasMaxLength(500)
                .HasColumnType("nvarchar(500)");
        });

        modelBuilder.Entity("SmartCar.Domain.Entities.BookingHoldEvent", b =>
        {
            b.Property<int>("BookingHoldEventId")
                .ValueGeneratedOnAdd()
                .HasColumnType("int");

            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingHoldEventId"));

            b.Property<int>("BookingId")
                .HasColumnType("int");

            b.Property<string>("CustomerId")
                .IsRequired()
                .HasMaxLength(450)
                .HasColumnType("nvarchar(450)");

            b.Property<bool>("IsWaived")
                .HasColumnType("bit");

            b.Property<DateTime>("OccurredAt")
                .HasColumnType("datetime2");

            b.Property<int>("VehicleId")
                .HasColumnType("int");

            b.Property<string>("WaiveReason")
                .HasMaxLength(500)
                .HasColumnType("nvarchar(500)");

            b.Property<DateTime?>("WaivedAt")
                .HasColumnType("datetime2");

            b.Property<string>("WaivedByAdminId")
                .HasMaxLength(450)
                .HasColumnType("nvarchar(450)");

            b.HasKey("BookingHoldEventId");

            b.HasIndex("BookingId")
                .IsUnique();

            b.HasIndex("CustomerId", "OccurredAt");

            b.HasIndex("VehicleId", "OccurredAt");

            b.ToTable("BookingHoldEvents");
        });

        modelBuilder.Entity("SmartCar.Domain.Entities.IdentityCaptureSession", b =>
        {
            b.Property<Guid>("IdentityCaptureSessionId")
                .ValueGeneratedOnAdd()
                .HasColumnType("uniqueidentifier");

            b.Property<int?>("BookingId")
                .HasColumnType("int");

            b.Property<string>("CaptureMethod")
                .HasMaxLength(50)
                .HasColumnType("nvarchar(50)");

            b.Property<DateTime?>("CompletedAt")
                .HasColumnType("datetime2");

            b.Property<DateTime?>("ConsumedAt")
                .HasColumnType("datetime2");

            b.Property<DateTime>("CreatedAt")
                .HasColumnType("datetime2");

            b.Property<string>("CreatedByUserId")
                .IsRequired()
                .HasMaxLength(450)
                .HasColumnType("nvarchar(450)");

            b.Property<DateTime>("ExpiresAt")
                .HasColumnType("datetime2");

            b.Property<string>("FallbackReason")
                .HasMaxLength(500)
                .HasColumnType("nvarchar(500)");

            b.Property<string>("ImagePath")
                .HasMaxLength(500)
                .HasColumnType("nvarchar(500)");

            b.Property<string>("Purpose")
                .IsRequired()
                .HasMaxLength(30)
                .HasColumnType("nvarchar(30)");

            b.Property<string>("TargetCustomerId")
                .IsRequired()
                .HasMaxLength(450)
                .HasColumnType("nvarchar(450)");

            b.Property<string>("TokenHash")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("nvarchar(128)");

            b.HasKey("IdentityCaptureSessionId");

            b.HasIndex("BookingId");

            b.HasIndex("TokenHash")
                .IsUnique();

            b.HasIndex("TargetCustomerId", "Purpose", "ExpiresAt");

            b.ToTable("IdentityCaptureSessions");
        });

        modelBuilder.Entity("SmartCar.Domain.Entities.BookingHoldEvent", b =>
        {
            b.HasOne("SmartCar.Domain.Entities.Booking", null)
                .WithMany()
                .HasForeignKey("BookingId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("SmartCar.Domain.Entities.IdentityCaptureSession", b =>
        {
            b.HasOne("SmartCar.Domain.Entities.Booking", null)
                .WithMany()
                .HasForeignKey("BookingId")
                .OnDelete(DeleteBehavior.Cascade);
        });
    }
}
