// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace SmartCar.Infrastructure.Persistence.Migrations;

partial class ApplicationDbContextModelSnapshot
{
    private static void BuildPart4(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity("SmartCar.Domain.Entities.VehicleReturn", b =>
            {
                b.Property<int>("VehicleReturnId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleReturnId"));

                b.Property<int>("BookingId")
                    .HasColumnType("int");

                b.Property<bool>("CustomerIdentityVerified")
                    .HasColumnType("bit");

                b.Property<string>("ExteriorCondition")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("FuelLevel")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("nvarchar(30)");

                b.Property<bool>("HasDamage")
                    .HasColumnType("bit");

                b.Property<DateTime?>("IdentityVerifiedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("IdentityVerifiedByStaffId")
                    .HasMaxLength(450)
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("ImagePaths")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("InteriorCondition")
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("IsLateReturn")
                    .HasColumnType("bit");

                b.Property<decimal>("LateFee")
                    .HasPrecision(18, 2)
                    .HasColumnType("decimal(18,2)");

                b.Property<int>("LateMinutes")
                    .HasColumnType("int");

                b.Property<int>("Mileage")
                    .HasColumnType("int");

                b.Property<string>("Notes")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("ReturnedAt")
                    .HasColumnType("datetime2");

                b.Property<bool>("SignedDocumentVerified")
                    .HasColumnType("bit");

                b.Property<DateTime?>("SignedDocumentVerifiedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("SignedDocumentVerifiedByStaffId")
                    .HasMaxLength(450)
                    .HasColumnType("nvarchar(450)");

                b.HasKey("VehicleReturnId");

                b.HasIndex("BookingId")
                    .IsUnique();

                b.ToTable("VehicleReturns");
            });

        modelBuilder.Entity("SmartCar.Infrastructure.Identity.ApplicationUser", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("nvarchar(450)");

                b.Property<int>("AccessFailedCount")
                    .HasColumnType("int");

                b.Property<string>("Address")
                    .HasMaxLength(250)
                    .HasColumnType("nvarchar(250)");

                b.Property<string>("AvatarPath")
                    .HasMaxLength(250)
                    .HasColumnType("nvarchar(250)");

                b.Property<string>("ConcurrencyStamp")
                    .IsConcurrencyToken()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("Email")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<bool>("EmailConfirmed")
                    .HasColumnType("bit");

                b.Property<string>("FullName")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit");

                b.Property<bool>("LockoutEnabled")
                    .HasColumnType("bit");

                b.Property<DateTimeOffset?>("LockoutEnd")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("NormalizedEmail")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("NormalizedUserName")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("PasswordHash")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("PhoneNumber")
                    .HasColumnType("nvarchar(450)");

                b.Property<bool>("PhoneNumberConfirmed")
                    .HasColumnType("bit");

                b.Property<string>("SecurityStamp")
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("TwoFactorEnabled")
                    .HasColumnType("bit");

                b.Property<string>("UserName")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.HasKey("Id");

                b.HasIndex("NormalizedEmail")
                    .HasDatabaseName("EmailIndex");

                b.HasIndex("NormalizedUserName")
                    .IsUnique()
                    .HasDatabaseName("UserNameIndex")
                    .HasFilter("[NormalizedUserName] IS NOT NULL");

                b.HasIndex("PhoneNumber")
                    .IsUnique()
                    .HasFilter("[PhoneNumber] IS NOT NULL");

                b.ToTable("AspNetUsers", (string)null);
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
            {
                b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                    .WithMany()
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
            {
                b.HasOne("SmartCar.Infrastructure.Identity.ApplicationUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
            {
                b.HasOne("SmartCar.Infrastructure.Identity.ApplicationUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
            {
                b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                    .WithMany()
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("SmartCar.Infrastructure.Identity.ApplicationUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
            {
                b.HasOne("SmartCar.Infrastructure.Identity.ApplicationUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("SmartCar.Domain.Entities.AdditionalCharge", b =>
            {
                b.HasOne("SmartCar.Domain.Entities.VehicleReturn", "VehicleReturn")
                    .WithMany("AdditionalCharges")
                    .HasForeignKey("VehicleReturnId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("VehicleReturn");
            });

        modelBuilder.Entity("SmartCar.Domain.Entities.Booking", b =>
            {
                b.HasOne("SmartCar.Infrastructure.Identity.ApplicationUser", null)
                    .WithMany()
                    .HasForeignKey("CustomerId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("SmartCar.Domain.Entities.Vehicle", "Vehicle")
                    .WithMany("Bookings")
                    .HasForeignKey("VehicleId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Vehicle");
            });

        modelBuilder.Entity("SmartCar.Domain.Entities.BookingExtension", b =>
            {
                b.HasOne("SmartCar.Domain.Entities.Booking", "Booking")
                    .WithMany("Extensions")
                    .HasForeignKey("BookingId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Booking");
            });

        modelBuilder.Entity("SmartCar.Domain.Entities.CustomerDocument", b =>
            {
                b.HasOne("SmartCar.Infrastructure.Identity.ApplicationUser", null)
                    .WithMany()
                    .HasForeignKey("CustomerId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

        modelBuilder.Entity("SmartCar.Domain.Entities.MaintenanceRecord", b =>
            {
                b.HasOne("SmartCar.Domain.Entities.Vehicle", "Vehicle")
                    .WithMany("MaintenanceRecords")
                    .HasForeignKey("VehicleId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Vehicle");
            });

        modelBuilder.Entity("SmartCar.Domain.Entities.Notification", b =>
            {
                b.HasOne("SmartCar.Infrastructure.Identity.ApplicationUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("SmartCar.Domain.Entities.Payment", b =>
            {
                b.HasOne("SmartCar.Domain.Entities.Booking", "Booking")
                    .WithMany("Payments")
                    .HasForeignKey("BookingId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("SmartCar.Domain.Entities.VehicleIncident", "VehicleIncident")
                    .WithMany("Payments")
                    .HasForeignKey("VehicleIncidentId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.Navigation("Booking");

                b.Navigation("VehicleIncident");
            });

        modelBuilder.Entity("SmartCar.Domain.Entities.Review", b =>
            {
                b.HasOne("SmartCar.Domain.Entities.Booking", "Booking")
                    .WithOne("Review")
                    .HasForeignKey("SmartCar.Domain.Entities.Review", "BookingId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Booking");
            });

        modelBuilder.Entity("SmartCar.Domain.Entities.Vehicle", b =>
            {
                b.HasOne("SmartCar.Domain.Entities.Brand", "Brand")
                    .WithMany("Vehicles")
                    .HasForeignKey("BrandId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Brand");
            });

        modelBuilder.Entity("SmartCar.Domain.Entities.VehicleDocument", b =>
            {
                b.HasOne("SmartCar.Domain.Entities.Vehicle", "Vehicle")
                    .WithMany("Documents")
                    .HasForeignKey("VehicleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Vehicle");
            });

        modelBuilder.Entity("SmartCar.Domain.Entities.VehicleHandover", b =>
            {
                b.HasOne("SmartCar.Domain.Entities.Booking", "Booking")
                    .WithOne("Handover")
                    .HasForeignKey("SmartCar.Domain.Entities.VehicleHandover", "BookingId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Booking");
            });

        modelBuilder.Entity("SmartCar.Domain.Entities.VehicleImage", b =>
            {
                b.HasOne("SmartCar.Domain.Entities.Vehicle", "Vehicle")
                    .WithMany("Images")
                    .HasForeignKey("VehicleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Vehicle");
            });

        modelBuilder.Entity("SmartCar.Domain.Entities.VehicleIncident", b =>
            {
                b.HasOne("SmartCar.Domain.Entities.Booking", "Booking")
                    .WithMany("Incidents")
                    .HasForeignKey("BookingId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.HasOne("SmartCar.Domain.Entities.Vehicle", "Vehicle")
                    .WithMany("Incidents")
                    .HasForeignKey("VehicleId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Booking");

                b.Navigation("Vehicle");
            });

        modelBuilder.Entity("SmartCar.Domain.Entities.VehicleReturn", b =>
            {
                b.HasOne("SmartCar.Domain.Entities.Booking", "Booking")
                    .WithOne("VehicleReturn")
                    .HasForeignKey("SmartCar.Domain.Entities.VehicleReturn", "BookingId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Booking");
            });

        modelBuilder.Entity("SmartCar.Domain.Entities.Booking", b =>
            {
                b.Navigation("Extensions");

                b.Navigation("Handover");

                b.Navigation("Incidents");

                b.Navigation("Payments");

                b.Navigation("Review");

                b.Navigation("VehicleReturn");
            });

        modelBuilder.Entity("SmartCar.Domain.Entities.Brand", b =>
            {
                b.Navigation("Vehicles");
            });

        modelBuilder.Entity("SmartCar.Domain.Entities.Vehicle", b =>
            {
                b.Navigation("Bookings");

                b.Navigation("Documents");

                b.Navigation("Images");

                b.Navigation("Incidents");

                b.Navigation("MaintenanceRecords");
            });

        modelBuilder.Entity("SmartCar.Domain.Entities.VehicleIncident", b =>
            {
                b.Navigation("Payments");
            });

        modelBuilder.Entity("SmartCar.Domain.Entities.VehicleReturn", b =>
            {
                b.Navigation("AdditionalCharges");
            });
    }
}
